# git-cliff ~ configuration file
# https://git-cliff.org/docs/configuration

[changelog]
header = """
# Changelog\n
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).\n
"""

# https://keats.github.io/tera/docs/#introduction
body = """
{% if version -%}
    ## [{{ version | trim_start_matches(pat="v") }}] - {{ timestamp | date(format="%Y-%m-%d") }}
{% else -%}
    ## [Unreleased]
{% endif -%}
{% for group, commits in commits | group_by(attribute="group") %}
    ### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }}\
    {% endfor %}
{% endfor %}\n
"""
# template for the changelog footer
footer = """
{% for release in releases -%}
    {% if release.version -%}
        {% if release.previous.version -%}
            [{{ release.version | trim_start_matches(pat="v") }}]: \
                https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}\
                    /compare/{{ release.previous.version }}..{{ release.version }}
        {% endif -%}
    {% else -%}
        [unreleased]: https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}\
            /compare/{{ release.previous.version }}..HEAD
    {% endif -%}
{% endfor %}
<!-- generated by git-cliff -->
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = false
commit_parsers = [
  { message = "^.*: [Aa]dd", group = "Added" },
  { message = "^.*: [Ss]upport", group = "Added" },
  { message = "^.*: [Rr]emove", group = "Removed" },
  { message = "^.*: [Dd]elete", group = "Removed" },
  { message = "^[Aa]dd", group = "Added" },
  { message = "^[Ss]upport", group = "Added" },
  { message = "^[Rr]emove", group = "Removed" },
  { message = "^[Dd]elete", group = "Removed" },
  { message = "^[Tt]est", group = "Fixed" },
  { message = "^[Ff]ix", group = "Fixed" },
  { message = "^.*: [Ff]ix", group = "Fixed" },
  { message = "^.*", group = "Changed" },
]
filter_commits = false
topo_order = false
sort_commits = "oldest"

[bump]
features_always_bump_minor = false
breaking_always_bump_major = false
initial_tag = "0.1.0"
