name: Create a release for the tag

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions: {}

jobs:
  release:
    runs-on: ubuntu-slim
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Generate Changelog
        uses: orhun/git-cliff-action@f50e11560dce63f7c33227798f90b924471a88b5 # v4.8.0
        with:
          config: .github/cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: .CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
      - name: Release
        run: gh release create -d -F .CHANGELOG.md
